### ISSUE TITLE
Extraneous requests

### ISSUE THREAD

**Issue by woodb03** [lognormal/boomerang#65] opened 2015-07-08 17:35 UTC
I have written a web filter to capture the beacon requests, and I recognize a page timing hit by the presence of t_done parameter, and an unload (which represents user think time) with rt.quit.

There is an unexpected request coming in and looks like this.  What does this represent?    It has very minimal data

GET /myapp/BeaconUrl?rt.start=none&rt.bstart=1436370217622&rt.end=1436370218232&r=https%3A%2F%2Faz-site1.blahblah.com%2Fmyapp%2Fservlet%2FSignonServlet&u=https%3A%2F%2Faz-site1.blahblah.com%2Fmyapp%2FmainMenu&v=0.9&vis.st=visible HTTP/1.1"

**Comment by bluesmoon** [comment] 2015-07-08 17:42
What plugins are you using and what code are you using to load and
initialise?

**Comment by woodb03** [comment] 2015-07-08 17:48
This is it:
<script src='/javascript/boomerang.js'></script>
<script src='/javascript/plugins/rt.js'></script>
<script src='/javascript/plugins/navtiming.js'></script>
<script>
       BOOMR.init({
               beacon_url: '/myapp/BeaconUrl',
               BW: { enabled: false},
               site_domain: 'blahblah.com',
               log: null
       });
</script>

**Comment by nicjansma** [comment] 2016-05-02 14:49
Hi @woodb03.  I have used the latest version of this repo with your code above, and am only seeing a single beacon being sent (e.g. to `/myapp/BeaconUrl`).

Does this still repro with the latest code?

Does it happen on every page load from your browser (if so, which browser/os?).  Otherwise, are you just seeing this in your logs?

Please let us know.

**Comment by woodb03** [comment] 2016-05-02 15:02
I do not see these requests when performing unit testing, only when the code gets deployed to an environment which receives lots of traffic.  I am able to ignore these so they don't cause a problem.  They represent less than 1% of the boomerang beacon requests.

**Comment by nicjansma** [comment] 2016-05-02 16:12
OK, interesting, thanks for your report.

This _might_ be caused by a pre-render from the browser causing Boomerang to send a beacon inappropriately.  We've fixed some issues around this and will be merging them into the OS library soon.

Closing this issue for now, please re-open if it becomes a larger issue.

**Closed by nicjansma** 2016-05-02 16:12 UTC
